# Generated by Django 2.0.7 on 2018-09-05 13:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default=' ', max_length=150)),
                ('answer', models.IntegerField(default=' ')),
                ('A', models.CharField(default=' ', max_length=150)),
                ('B', models.CharField(default=' ', max_length=150)),
                ('C', models.CharField(default=' ', max_length=150)),
                ('D', models.CharField(default=' ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Question_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_list', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=1)),
                ('question_skip_count', models.IntegerField(default=0)),
                ('perception_present', models.IntegerField(default=2)),
                ('incr', models.IntegerField(default=4, null=True)),
                ('decr', models.IntegerField(default=2, null=True)),
                ('perception_active', models.IntegerField(default=0)),
                ('perception_question_count', models.IntegerField(default=3)),
                ('timer', models.TimeField(default='00:00')),
                ('email_1', models.EmailField(default='player_1@gmail.com', max_length=20, validators=[django.core.validators.EmailValidator()])),
                ('email_2', models.EmailField(default='player_2@gmail.com', max_length=20, validators=[django.core.validators.EmailValidator()])),
                ('name_1', models.CharField(default='player_1', max_length=20)),
                ('name_2', models.CharField(default='player_2', max_length=20)),
                ('number_1', models.IntegerField(default=0)),
                ('number_2', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
