# Generated by Django 2.0.7 on 2018-09-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mcq_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='halt_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
