# Generated by Django 2.0.7 on 2018-09-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180905_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='halt_time',
        ),
    ]
