# Generated by Django 2.0.7 on 2018-09-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180905_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
