# Generated by Django 2.0.7 on 2018-09-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mcq_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
