# Generated by Django 2.0.7 on 2018-09-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='halt_start_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='halt_stop_time',
            field=models.IntegerField(default=0),
        ),
    ]
