# Generated by Django 2.0.4 on 2018-09-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ad_pass',
            field=models.CharField(default='abcd', max_length=20),
        ),
    ]
