# Generated by Django 2.0.4 on 2018-09-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_ad_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='logout_time',
            field=models.IntegerField(default=0),
        ),
    ]
