# Generated by Django 2.0.4 on 2018-09-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='timer',
            field=models.IntegerField(default=0),
        ),
    ]
