# Generated by Django 2.0.4 on 2018-09-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180907_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='logout_time',
            new_name='add_time',
        ),
    ]
