# Generated by Django 2.0.7 on 2018-09-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180907_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='halt_start_time',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='halt_stop_time',
        ),
    ]
