# Generated by Django 2.0.7 on 2018-09-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180909_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skip_count',
            field=models.IntegerField(default=2),
        ),
    ]
