# Generated by Django 2.0.4 on 2018-09-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180909_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=2),
        ),
    ]
