# Generated by Django 2.0.7 on 2018-09-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userprofile_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='answer',
        ),
        migrations.AddField(
            model_name='question_list',
            name='answer',
            field=models.IntegerField(default=0),
        ),
    ]
